/// Flutter icons KejaClientSvg
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KejaClientSvg
///      fonts:
///       - asset: fonts/KejaClientSvg.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KejaClientSvg {
  KejaClientSvg._();

  static const _kFontFam = 'KejaClientSvg';

  static const IconData Kejanotification = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData humberger = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData grouphome = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData vectorcreate = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData vectorheart = const IconData(0xe804, fontFamily: _kFontFam);
}
